version: '2'
services:
  #Service for nameserver
  namesrv:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqnamesrv
    network_mode: host
#    ports:
#      - 9876:9876
    volumes:
      - ./node1/data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  broker-master:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqbroker
    network_mode: host
#    links:
#      - namesrv
#    ports:
#      - 10909:10909
#      - 10911:10911
#      - 10912:10912
    environment:
      - NAMESRV_ADDR= 10.140.0.2:9876
    volumes:
      - ./node1/data/broker/logs:/home/rocketmq/logs
      - ./node1/data/broker/store:/home/rocketmq/store
      - ./node1/data/broker/conf/broker-a.properties:/opt/rocketmq-4.5.0/conf/broker.conf
#      - ./node1/data/broker/conf/broker.conf:/opt/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.5.0/conf/broker.conf

  #Service for another broker -- broker1
  broker-slave:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqbroker-b
    network_mode: host
#    links:
#      - namesrv
#    ports:
#      - 10929:10909
#      - 10931:10911
#      - 10932:10912
    environment:
      - NAMESRV_ADDR=10.140.0.2:9876
    volumes:
      - ./node1/data1/broker/logs:/home/rocketmq/logs
      - ./node1/data1/broker/store:/home/rocketmq/store
      - ./node1/data1/broker/conf/broker-slave.conf:/opt/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.5.0/conf/broker.conf
  rocketmq-console-ng:
    container_name: rmqconsole
    image: styletang/rocketmq-console-ng:latest
    network_mode: host
    depends_on:
      - broker-master
      - namesrv
#    ports:
#        - 8080:8080
    environment:
        NAMESRV_ADDR: "10.140.0.2:9876"
