version: '2'
services:
  #Service for nameserver
  namesrv:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqnamesrv
    network_mode: host
#    ports:
#      - 9876:9876
    volumes:
      - ./node3/data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  broker-master:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqbroker
    network_mode: host
#    links:
#      - namesrv
#    ports:
#      - 10909:10909
#      - 10911:10911
#      - 10912:10912
    environment:
      - NAMESRV_ADDR= 10.140.0.7:9876
    volumes:
      - ./node3/data/broker/logs:/home/rocketmq/logs
      - ./node3/data/broker/store:/home/rocketmq/store
      - ./node3/data/broker/conf/broker-c.properties:/opt/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.5.0/conf/broker.conf

  #Service for another broker -- broker1
  broker-slave:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqbroker-b
    network_mode: host
#    links:
#      - namesrv
#    ports:
#      - 10929:10909
#      - 10931:10911
#      - 10932:10912
    environment:
      - NAMESRV_ADDR=10.140.0.7:9876
    volumes:
      - ./node3/data1/broker/logs:/home/rocketmq/logs
      - ./node3/data1/broker/store:/home/rocketmq/store
      - ./node3/data1/broker/conf/broker-slave.conf:/opt/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.5.0/conf/broker.conf
